### ISSUE TITLE
Better errror handling

### ISSUE THREAD

**Issue by afreickmann** [adventurebrew/magos#3]
It would be great if you could maybe print out the problematic code line in the error handling, it would be very helpful to identify the correct line within the script.
`Traceback (most recent call last):
  File "magos\magos.py", line 449, in <module>
  File "magos\magos.py", line 201, in rewrite_tables
  File "magos\magos.py", line 201, in <genexpr>
  File "magos\gamepc_script.py", line 252, in __bytes__
  File "magos\gamepc_script.py", line 232, in __bytes__
  File "magos\gamepc_script.py", line 232, in <genexpr>
  File "magos\gamepc_script.py", line 214, in __bytes__
  File "magos\gamepc_script.py", line 214, in <genexpr>
  File "magos\gamepc_script.py", line 167, in __bytes__
ValueError: bytes must be in range(0, 256)
[9172] Failed to execute script 'magos' due to unhandled exception!`

**Comment by BLooperZ** [comment]
Thank you for your suggestion, I have added more information when an error occurs while parsing the script pointing to the offending line
for example:
```
ERROR: Cannot parse scripts file at
  FILE: GAMEPC
  SUBROUTINE: (0, 0)
  LINE: 44
  BLOCK: 2
Block starts at scripts.txt:47:
==>     (0x47) -> PROCESS 50 4 <-
        (0x47) PROCESS 84
        (0xa2) PRINT_STR 1 0 389 150 // {That's just plain silly.}

PROCESS expects 1 parameters of types N but 2 given: 50 4
```
